# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-28 10:01
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paduka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prototype_id', models.CharField(max_length=6, verbose_name='Number')),
                ('season', models.CharField(max_length=20)),
                ('division', models.CharField(choices=[('Sandal', 'Sandal'), ('Slipper', 'Slipper'), ('Espadrille', 'Espadrille')], max_length=50)),
                ('color_description', multiselectfield.db.fields.MultiSelectField(choices=[('Jute Color', 'Jute Color'), ('Red', 'Red'), ('Blue', 'Blue'), ('Green', 'Green'), ('Yellow', 'Yellow'), ('White', 'White'), ('Black', 'Black'), ('Purple', 'Purple'), ('Maroon', 'Maroon'), ('Orange', 'Orange'), ('Black & White', 'Black & White'), ('Olive Green', 'Olive Green'), ('Navy blue', 'Navy Blue'), ('Dark Grey', 'Dark Grey'), ('Stripe', 'Stripe')], max_length=118)),
                ('price', models.FloatField(null=True)),
                ('upper', models.CharField(max_length=100)),
                ('footbed', models.CharField(max_length=100)),
                ('footbed_skin', models.CharField(max_length=100)),
                ('edge_treatment_upper', models.CharField(max_length=100)),
                ('edge_color', models.CharField(max_length=100)),
                ('edge_treatment_sole', models.CharField(max_length=100)),
                ('logo', models.CharField(max_length=50)),
                ('heel', models.CharField(max_length=50)),
            ],
        ),
    ]
