# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-28 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paduka',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
