# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-29 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_paduka_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paduka',
            name='prototype_id',
            field=models.CharField(max_length=10, verbose_name='Number'),
        ),
    ]
